version: '2'

services:
  ateliersoude_nginx:
    build:
      context: ../.
      dockerfile: ./deployment/nginx/Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    # restart: unless-stopped
    depends_on:
      - django
    volumes:
      - ../ateliersoude_static:/srv/static \
      - ../ateliersoude_media:/srv/media \
